// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRgr2xQIQzV2DVINuDoqbdRCSoClDaiU',
    appId: '1:199637025662:web:72e723fddfc5bac3e2a92f',
    messagingSenderId: '199637025662',
    projectId: 'resistancechat',
    authDomain: 'resistancechat.firebaseapp.com',
    storageBucket: 'resistancechat.firebasestorage.app',
    measurementId: 'G-M2588TGEQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gkNXWkJ1DQ7aB4uuULnflP4eAAVLeT4',
    appId: '1:199637025662:android:c3be2aecf0c6270be2a92f',
    messagingSenderId: '199637025662',
    projectId: 'resistancechat',
    storageBucket: 'resistancechat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAueXldDM9HyXpRS5IuKAiBFtryFarWrfY',
    appId: '1:199637025662:ios:c64e85c236f884afe2a92f',
    messagingSenderId: '199637025662',
    projectId: 'resistancechat',
    storageBucket: 'resistancechat.firebasestorage.app',
    iosBundleId: 'com.example.resistance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAueXldDM9HyXpRS5IuKAiBFtryFarWrfY',
    appId: '1:199637025662:ios:c64e85c236f884afe2a92f',
    messagingSenderId: '199637025662',
    projectId: 'resistancechat',
    storageBucket: 'resistancechat.firebasestorage.app',
    iosBundleId: 'com.example.resistance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRgr2xQIQzV2DVINuDoqbdRCSoClDaiU',
    appId: '1:199637025662:web:2f241c518b3e1a79e2a92f',
    messagingSenderId: '199637025662',
    projectId: 'resistancechat',
    authDomain: 'resistancechat.firebaseapp.com',
    storageBucket: 'resistancechat.firebasestorage.app',
    measurementId: 'G-SXC2BY4R6F',
  );

}